modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "auto_switch_elytra"
version = "${version}"
displayName = "Auto Switch Elytra"
authors = "fakeneko"
description = '''
Auto Switch Elytra
'''
logoFile = "auto_switch_elytra.png"

[[dependencies.auto_switch_elytra]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.auto_switch_elytra]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"


[[mixins]]
config = "auto_switch_elytra.mixins.json"
